#!/bin/bash
# Minecraft Server Startup Script
# Supports Forge, Spigot, and Paper servers with Docker compatibility

# Default values for environment variables (can be overridden)
TYPE=${TYPE:-"FORGE"}
MCVERSION=${MCVERSION:-"1.20.1"}
FORGEVERSION=${FORGEVERSION:-"47.2.0"}
MEMORY=${MEMORY:-"2G"}
EULA=${EULA:-"false"}

echo "========================================"
echo "Minecraft Server Startup"
echo "========================================"
echo "Server Type:    $TYPE"
echo "Minecraft:      $MCVERSION"
[ "$TYPE" = "FORGE" ] && echo "Forge Version:  $FORGEVERSION"
echo "Memory:         $MEMORY"
echo "EULA Accepted:  $EULA"
echo "========================================"

# Function to create eula.txt if EULA=true
create_eula_if_needed() {
    if [ "$EULA" = "true" ] && [ ! -f eula.txt ]; then
        echo "Auto-accepting EULA (EULA=true)..."
        echo "# Generated by startup script" > eula.txt
        echo "eula=true" >> eula.txt
        echo "✓ eula.txt created"
    fi
}

# Function to handle errors
handle_error() {
    echo "❌ ERROR: $1"
    exit 1
}

# Function to download with retry
download_with_retry() {
    local url="$1"
    local output="$2"
    local max_retries=3
    local retry_count=0
    
    while [ $retry_count -lt $max_retries ]; do
        echo "Download attempt $((retry_count + 1))/$max_retries..."
        if wget --progress=bar:force:noscroll "$url" -O "$output"; then
            return 0
        fi
        retry_count=$((retry_count + 1))
        if [ $retry_count -lt $max_retries ]; then
            echo "Retrying in 5 seconds..."
            sleep 5
        fi
    done
    return 1
}

# Create eula.txt if needed
create_eula_if_needed

# Wait for eula.txt if not present and EULA is not true
if [ ! -f eula.txt ]; then
    echo "⚠️  Waiting for EULA acceptance..."
    echo "   To auto-accept, set environment variable: EULA=true"
    while [ ! -f eula.txt ]; do
        echo "   Waiting for eula.txt to be created..."
        sleep 10
    done
    echo "✓ EULA accepted"
fi

# Start the server based on type
case "$TYPE" in
    "FORGE")
        if [ ! -f server.jar ]; then
            echo "📥 Installing Forge Server..."
            
            # КЛЮЧЕВОЕ ИЗМЕНЕНИЕ: Формируем "версию для ссылки" на основе стандартного формата Forge
            # Этот формат (1.20.1-47.2.0) является наиболее распространенным.
            FORGE_VERSION_STRING="${MCVERSION}-${FORGEVERSION}"
            FORGE_INSTALLER="forge-${FORGE_VERSION_STRING}-installer.jar"
            
            # КЛЮЧЕВОЕ ИЗМЕНЕНИЕ: Используем исправленный URL
            # Старая структура: .../forge/${MCVERSION}-${FORGEVERSION}/...
            # Часто корректная структура: .../forge/${FORGE_VERSION_STRING}/...
            DOWNLOAD_URL="https://maven.minecraftforge.net/net/minecraftforge/forge/${FORGE_VERSION_STRING}/${FORGE_INSTALLER}"
            
            echo "   Generated Version String: ${FORGE_VERSION_STRING}"
            echo "   Attempting Download From: ${DOWNLOAD_URL}"
            
            # ... (далее идет код скачивания wget, такой же как у вас)
            if ! download_with_retry "${DOWNLOAD_URL}" "${FORGE_INSTALLER}"; then
                # Если скачивание по основной схеме не удалось, пробуем альтернативный URL
                echo "   Primary URL failed, trying alternative pattern..."
                ALTERNATIVE_URL="https://maven.minecraftforge.net/net/minecraftforge/forge/${MCVERSION}-${FORGEVERSION}-${MCVERSION}/${FORGE_INSTALLER}"
                echo "   Attempting: ${ALTERNATIVE_URL}"
                if ! download_with_retry "${ALTERNATIVE_URL}" "${FORGE_INSTALLER}"; then
                    handle_error "All download attempts for Forge installer failed. Please check MCVERSION (${MCVERSION}) and FORGEVERSION (${FORGEVERSION})."
                fi
            fi
            
            echo "🔍 Searching for Forge server jar..."
            
            # Patterns to search for Forge jar
            local patterns=(
                "forge-${MCVERSION}-${FORGEVERSION}.jar"
                "forge-${MCVERSION}-${FORGEVERSION}-universal.jar"
                "forge-${MCVERSION}-${FORGEVERSION}-server.jar"
                "forge.jar"
            )
            
            local found_jar=""
            for pattern in "${patterns[@]}"; do
                if [ -f "$pattern" ]; then
                    found_jar="$pattern"
                    break
                fi
            done
            
            # Search in libraries directory
            if [ -z "$found_jar" ]; then
                local lib_jar=$(find . -path "*/libraries/net/minecraftforge/forge/${MCVERSION}-${FORGEVERSION}/forge-*.jar" -type f 2>/dev/null | head -1)
                if [ -n "$lib_jar" ]; then
                    found_jar="$lib_jar"
                fi
            fi
            
            # Last resort: find any forge jar
            if [ -z "$found_jar" ]; then
                local any_jar=$(find . -name "forge-*.jar" -type f | grep -v installer | head -1)
                if [ -n "$any_jar" ]; then
                    found_jar="$any_jar"
                fi
            fi
            
            if [ -n "$found_jar" ]; then
                echo "   Found: $found_jar"
                cp "$found_jar" server.jar
                echo "✓ Forge installed as server.jar"
            else
                echo "   Available jar files:"
                find . -name "*.jar" -type f | while read -r jar; do
                    echo "   - $jar"
                done
                handle_error "Could not find Forge server jar after installation"
            fi
            
            # Clean up
            rm -f "${FORGE_INSTALLER}" 2>/dev/null
            echo "   Cleanup completed"
        else
            echo "✓ Using existing server.jar"
        fi
        
        echo "🚀 Starting Forge server with ${MEMORY} RAM..."
        exec java -Xms${MEMORY} -Xmx${MEMORY} \
            -XX:+UseG1GC \
            -XX:+UnlockExperimentalVMOptions \
            -XX:MaxGCPauseMillis=100 \
            -XX:+DisableExplicitGC \
            -XX:TargetSurvivorRatio=90 \
            -XX:G1NewSizePercent=50 \
            -XX:G1MaxNewSizePercent=80 \
            -XX:G1MixedGCLiveThresholdPercent=35 \
            -XX:+AlwaysPreTouch \
            -XX:+ParallelRefProcEnabled \
            -Dlog4j2.formatMsgNoLookups=true \
            -jar server.jar nogui
        ;;
        
    "SPIGOT")
        if [ ! -f server.jar ]; then
            echo "📥 Downloading Spigot server..."
            SPIGOT_URL="https://cdn.getbukkit.org/spigot/spigot-${MCVERSION}.jar"
            
            if ! download_with_retry "${SPIGOT_URL}" "spigot-${MCVERSION}.jar"; then
                handle_error "Failed to download Spigot"
            fi
            
            if [ ! -f "spigot-${MCVERSION}.jar" ]; then
                handle_error "Spigot jar not found after download"
            fi
            
            mv "spigot-${MCVERSION}.jar" server.jar
            echo "✓ Spigot downloaded as server.jar"
        fi
        
        echo "🚀 Starting Spigot server with ${MEMORY} RAM..."
        exec java -Xms${MEMORY} -Xmx${MEMORY} -jar server.jar nogui
        ;;
        
    "PAPER")
        if [ ! -f server.jar ]; then
            echo "📥 Downloading Paper server..."
            
            # Get build info from PaperMC API
            API_URL="https://api.papermc.io/v2/projects/paper/versions/${MCVERSION}"
            echo "   Fetching build info from PaperMC API..."
            
            # Use jq if available, otherwise use grep
            if command -v jq >/dev/null 2>&1; then
                BUILD_INFO=$(wget -qO- "${API_URL}")
                LATEST_BUILD=$(echo "$BUILD_INFO" | jq -r '.builds[-1]')
            else
                # Fallback to grep
                BUILD_INFO=$(wget -qO- "${API_URL}")
                LATEST_BUILD=$(echo "$BUILD_INFO" | grep -o '"builds":\[[^]]*' | tail -1 | grep -o '[0-9]\+' | tail -1)
            fi
            
            if [ -z "$LATEST_BUILD" ] || [ "$LATEST_BUILD" = "null" ]; then
                handle_error "Could not determine latest Paper build for ${MCVERSION}"
            fi
            
            echo "   Latest build: ${LATEST_BUILD}"
            PAPER_URL="https://api.papermc.io/v2/projects/paper/versions/${MCVERSION}/builds/${LATEST_BUILD}/downloads/paper-${MCVERSION}-${LATEST_BUILD}.jar"
            
            echo "   Downloading: ${PAPER_URL}"
            if ! download_with_retry "${PAPER_URL}" "paper-${MCVERSION}.jar"; then
                handle_error "Failed to download Paper"
            fi
            
            mv "paper-${MCVERSION}.jar" server.jar
            echo "✓ Paper downloaded as server.jar"
        fi
        
        echo "🚀 Starting Paper server with ${MEMORY} RAM..."
        exec java -Xms${MEMORY} -Xmx${MEMORY} \
            -XX:+UseG1GC \
            -XX:+UnlockExperimentalVMOptions \
            -XX:MaxGCPauseMillis=100 \
            -jar server.jar nogui
        ;;
        
    *)
        handle_error "Unsupported server type: '$TYPE'. Must be one of: FORGE, SPIGOT, PAPER"
        ;;
esac